version: 2

updates:
  # ------------------------------
  # Firebase Functions (Node/TS)
  # ------------------------------
  - package-ecosystem: "npm"
    directory: "/Universe/functions"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "direct"
      - dependency-type: "production"

  # ------------------------------
  # Android / Gradle Dependencies
  # ------------------------------
  - package-ecosystem: "gradle"
    directory: "/Universe"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-name: "org.jetbrains.kotlin:*"
      - dependency-name: "com.android.tools.build:gradle"
        update-types: [ "version-update:semver-major" ]

  # ------------------------------
  # GitHub Actions
  # ------------------------------
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
