name: Full Application CI

on:
  push:
  pull_request:

jobs:

  firebase:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Firebase dependencies
        working-directory: Universe/functions
        run: npm install

      - name: Build Firebase (ignore warnings)
        working-directory: Universe/functions
        run: npm run build --if-present || true


  android:
    runs-on: ubuntu-latest
    needs: firebase

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17

      - name: Make Gradlew executable
        working-directory: Universe
        run: chmod +x ./gradlew

      - name: Build Android App
        working-directory: Universe
        run: ./gradlew assembleDebug --stacktrace

      - name: Test Android
        working-directory: Universe
        run: ./gradlew test --stacktrace
